### ISSUE TITLE
Excel file not generated

### ISSUE THREAD

**Issue by rodrigoffonseca** [RenatoGregio/AzureResourceInventory#2]
I found an issue while I was testing the tool, It ran OK but no excel file was created after it completed.
The folder C:\AzureGrinder was empty and no excel report was created:
Report Complete. Total Runtime was: 4.79 Minutes
Total Resources: 2009
Total Advisories: 1247
Total Security Advisories: 1022

Excel file saved at: C:\AzureGrinder\AzureGrinder_Report_2020-12-04_16_52.xlsx

I had to manually install the Powershell Module ImportExcel using "install-module importexcel" and then I was able to successful run the report.

**Comment by RenatoGregio** [comment]
Hello Rodrigo, 

Thank you for your report. 

This issue was occurring by a Bug. During the script execution ARI have some steps to identify if "ImportExcel" Module is installed. If not they try to install, if it's not possible they stop script excution. 
This step wasn't working properly and We fixed on 1.2.2 version.
